### ISSUE TITLE
Tablice wielowymiarowe, zadanie 3

### ISSUE THREAD

**Issue by matek997** [SowinskiMateusz/wsei-javascript-zadania#2]
Niejasne zadanie.
Dla tablicy [ [0,1], [2,3] ] wyjściem powinno być :
0, 1,
2, 3
czy
0
1
2
3
?

**Comment by SowinskiMateusz** [comment]
Chodziło mi o wypisanie w postaci:

0
1
2
3

dodam przykład do tego zadania - dziękuję za zwrócenie uwagi.
