### ISSUE TITLE
11_Dom_Eventy zadanie 0a

### ISSUE THREAD

**Issue by grzegorzociepka** [SowinskiMateusz/wsei-javascript-zadania#4]
W treści zadania 0a w dziale 11_dom_eventy jest polecenie żeby uruchomić stronę zadanieWykladowca.html
Taka strona nie została dołączona do zadania, chyba że chodzi o zadanie00.html

**Comment by SowinskiMateusz** [comment]
tak chodzi o zadanie00.html
