### ISSUE TITLE
12_DOM_Poruszanie_sie_po_drzewie

### ISSUE THREAD

**Issue by grzegorzociepka** [SowinskiMateusz/wsei-javascript-zadania#7]
W zadaniu 0, podpunkcie 3, mamy wyciągnąć dany element, potem jego dziadka i jego ostatnie dziecko. Tu pojawia się problem, ponieważ element który powinniśmy wyciągnąć żeby poprawnie rozwiązać zadanie jest tak na prawdć przedostatnim na liście.
Problem wynika z tego że nowe linie zrobione przy pomocy entera są traktowane jako osobny node element. Takich elementów w liście oczywiście pojawia się więcej :)
Nie wiem czy to kwestia przeglądarki czy formatowania kodu, ja korzystam z google chrome.

**Comment by Arvade** [comment]
Z tego co widzę, to wszystko jest w porządku. Spróbuj jeszcze raz uważne prześledzić to zadanie.  

Jeśli masz problem z tym zadaniem to ewentualnie jest u mnie rozwiązanie - dla prostoty każdy krok wyciągnięty jest osobno.

**Comment by grzegorzociepka** [comment]
@Arvade robiłem je w podobny sposób, po prostu nie wiem dlaczego łamanie linii traktował jako dodatkowy element node.

**Comment by SowinskiMateusz** [comment]
jest różnica pomiędzy nodes a element. nodes wyciąga wszystko a element tylko elementy. Zobacz screen poniżej. ChildrenNodes wyciągnął zwykły tekst, natomiast children nie wyciągnął żadnych elementów ponieważ w tym konretnym nie ma nic poza tekstem. Jak będziemy przy tym zadaniu to przypomnijcie to bardziej szczegółowo to omówię.

![image](https://user-images.githubusercontent.com/9249982/66824722-1e35bc80-ef49-11e9-9b8e-fea0a718e3f5.png)
